### ISSUE TITLE
Required versions of Python and dependencies

### ISSUE THREAD

**Issue by isgulkov** [danielkelshaw/PyUAVSIM#47]
So, I install the stuff inside a 3.10 `pipenv` environment:

```bash
$ pipenv run python -V       
Python 3.10.9
```

```bash
$ pipenv graph
PyOpenGL==3.1.6
PyQt6==6.4.0
  - PyQt6-Qt6 [required: >=6.4.0, installed: 6.4.2]
  - PyQt6-sip [required: >=13.4,<14, installed: 13.4.0]
pyqtgraph==0.13.1
  - numpy [required: >=1.20.0, installed: 1.24.1]
PyYAML==6.0
scipy==1.10.0
  - numpy [required: >=1.19.5,<1.27.0, installed: 1.24.1]
```

---

Trying to run `sim_example.py` fails like this:

```bash
$ pipenv run python sim_example.py  
/Users/isgulkov/Code/stuff/PyUAVSIM/uavsim/uav_dynamics.py:374: RuntimeWarning: invalid value encountered in sqrt
  omega = (-b + np.sqrt(b ** 2 - 4 * a * c)) / (2 * a)
Traceback (most recent call last):
  File "/Users/isgulkov/Code/stuff/PyUAVSIM/sim_example.py", line 27, in <module>
    uav_viewer = uavsim.UAVViewer()
  File "/Users/isgulkov/Code/stuff/PyUAVSIM/uavsim/plotting/uav_viewer.py", line 11, in __init__
    self.app = pg.QtGui.QApplication([])
AttributeError: module 'pyqtgraph.Qt.QtGui' has no attribute 'QApplication'. Did you mean: 'QGuiApplication'?
```

Clearly, I have a wrong version of something — either `pyqtgraph` or `PyQt`.

Could you please specify the versions this applications runs on?

**Comment by danielkelshaw** [comment]
Hi, thanks for reaching out! It's been quite a while since I last looked at this so I cannot recall. Seems that at the time I was ignorant of the importance of versioning the requirements haha.

You may have to use `PyQT4` or `PyQT5`. If you find some working requirements I would welcome a pull request to fix this!

Sorry I couldn't be of more help!
